.\"
.\" $Id: getcap.8,v 1.1.1.1 1999/04/17 22:16:31 morgan Exp $
.\" written by Andrew Main <zefram@dcs.warwick.ac.uk>
.\"
.TH GETCAP 8 "26th April 1997"
.SH NAME
getcap \- examine file capabilities
.SH SYNOPSIS
\fBgetcap\fP \fIfilename\fP [ ... ]
.SH DESCRIPTION
.B getcap
displays the name and capabilities of each specified
.IR filename .
One file per line.
.SH "SEE ALSO"
.IR cap_get_file (3),
.IR cap_to_text (3),
.IR setcap (8)
